version: '3.8'

services:
  e-learning-backend:
    build: ./e-learning-backend
    ports:
      - "8080:8080"
    # Add other configurations like volumes, networks, etc., if needed

  e-learning-frontend:
    build: ./e-learning-frontend
    ports:
      - "3000:80" # Assuming React app runs on port 3000 in the container
    # Add other configurations like volumes, networks, etc., if needed

  quick-bucket:
    build: ./quick-bucket
    ports:
      - "9999:9999"
    volumes:
      - type: bind
        source: /media/kamran/nvme_ssd/Projects/E-Learning-Platform/quick-bucket-uploads
        target: /app/uploads
    # volumes:
    #   - quick-bucket-uploads:/app/uploads 
    # Add other configurations like ports, networks, etc., if needed

# Define the volume in the top-level 'volumes' section if needed for other services
#volumes:
  # Define other volumes here if needed for other services
# volumes:
#   quick-bucket-uploads:
#     driver: local
#     driver_opts:
#       o: bind
#       type: none
#       device: /quick-bucket-uploads

# version: '3.8'

# services:
#   e-learning-backend:
#     build: ./e-learning-backend
#     ports:
#       - "8080:8080"
#     # Add other configurations like volumes, networks, etc., if needed

#   e-learning-frontend:
#     build: ./e-learning-frontend
#     ports:
#       - "3000:3000" # Assuming React app runs on port 3000 in the container
#     # Add other configurations like volumes, networks, etc., if needed

#   quick-bucket:
#     build: ./quick-bucket
#     ports:
#       - "9999:9999"
#     volumes:
#       - quick-bucket-uploads:app/uploads
#     # Add other configurations like volumes, networks, etc., if needed

#   # nginx:
#   #   image: nginx:latest
#   #   ports:
#   #     - "80:80"
#   #   volumes:
#   #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
#   #   depends_on:
#   #     - e-learning-backend
#   #     - e-learning-frontend
#   #     - quick-bucket

# volumes:
#   quick-bucket-uploads:
#     # Define volume for quick-bucket uploads
#     driver: local # Define the driver and options under the volume name
#     driver_opts:
#       type: none
#       device: /quick-bucket-uploads
#       o: bind
